name: Deploy Infrastructure

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  terraform_apply:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # - name: Install Terraform
    #   env: 
    #   run:

    - name: Verify Terraform Version
      run: terraform --version

    # - name: Terraform Init
    #   env: 
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    #   run: terraform init -input=false
    
    - name: List Files in Working Directory
      run: ls -lR
    
    - name: Terraform Validation
      run: terraform validate