name: Deploy Infrastructure

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  terraform_apply:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout 
      uses: actions/checkout@v1

   # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7

    - name: Verify Terraform Version
      run: terraform --version

    - name: List Files in Working Directory
      run: ls -lR
    
